[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "vape"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
set-claude = "ln -sf $PIXI_PROJECT_ROOT/conf/.claude/settings.json ~/.claude/settings.json"
set-ccstatusline = "ln -sf $PIXI_PROJECT_ROOT/conf/ccstatusline/settings.json ~/.config/ccstatusline/settings.json"
init.depends-on = ["set-claude", "set-ccstatusline"]

[dependencies]
pnpm = "*"

[activation.env]
PATH = "$PIXI_PROJECT_ROOT/node_modules/.bin:$PATH"
