[workspace]
authors = ["fecet <xiezej@gmail.com>"]
channels = ["https://repo.prefix.dev/meta-forge", "conda-forge"]
name = "vape"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
pnpm = "*"

[activation.env]
PATH = "$PIXI_PROJECT_ROOT/node_modules/.bin:$PATH"
